--curso  https://www.udemy.com/course/oracle-developer-sql-e-plsql/
CREATE TABLE CADASTRO
(
    NOME VARCHAR(50) NOT NULL,
    DOCTO VARCHAR(20) NOT NULL
    );
    
-- INSERE DADOS NA TABELA CADASTRO
INSERT INTO CADASTRO VALUES('ANDRE', '123456');
INSERT INTO CADASTRO VALUES('JOAO', '123456');
INSERT INTO CADASTRO VALUES('PEDRO', '123456');

-- VERIFICANDO REGISTROS
SELECT * FROM CADASTRO;


--RETORNA A TABELA PARA O ESTADO ANTERIOS DO BEGIN TRANSACTION
-- ROLLBACK
-- RECOMENDADO UTILIZAR COM PROCEDURES E NÃP COM TRIGGERS
ROLLBACK;

-EFETIVAR AS INFORMACOES NA TABELA DO BANCO DE DADOS
COMMIT;


DELETE FROM CADASTRO;

SELECT * FROM CADASTRO;
-- SAVEPOINT
-- INSERE DADOS NA TABELA CADASTRO
INSERT INTO CADASTRO VALUES('ANDRE', '123456');
SAVEPOINT P1;
INSERT INTO CADASTRO VALUES('JOAO', '123456');
SAVEPOINT P2;
INSERT INTO CADASTRO VALUES('PEDRO', '123456');
SAVEPOINT P3;

-- ROLLBACK ATE O SAVEPOINT
ROLLBACK TO SAVEPOINT P2;