--curso  https://www.udemy.com/course/oracle-developer-sql-e-plsql/
-- EXEMPLO UNION ALL
    SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM employees
        UNION ALL
        SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM employees
        ORDER BY 1;

-- EXEMPLO COM UNION EFETUA O DISTINCT 
    SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM employees
        UNION
        SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM employees
        ORDER BY 1;

-- EXEMPLO COM UNION CAMPOS DIFERENTES POREM COM MESMA CARACTERISTICA DE TIPO,
    SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM employees
        UNION
        SELECT EMPLOYEE_ID, LAST_NAME, SALARY FROM employees
        ORDER BY 1;

-- EXEMPLO USANDO UNION
    SELECT ANO, ESTADO FROM SENSO WHERE ANO=2014
        UNION
        SELECT ANO, ESTADO FROM SENSO WHERE ANO=2013
        ORDER BY 1;

-- USANDO UNION ALL
    SELECT ANO, ESTADO FROM SENSO WHERE ANO=2014
        UNION ALL
        SELECT ANO, ESTADO FROM SENSO WHERE ANO=2013;

    SELECT ESTADO FROM SENSO WHERE ANO=2014
        UNION
        SELECT ESTADO FROM SENSO WHERE ANO=2013;

