--curso  https://www.udemy.com/course/oracle-developer-sql-e-plsql/
-- TABELAS TEMPORARIAS

CREATE GLOBAL TEMPORARY TABLE minha_temp(
    id number,
    nome varchar2(20))
    ON COMMIT DELETE ROWS;
    
--INSERINDO DADOS
INSERT INTO MINHA_TEMP VALUES(1, 'TESTE1');
INSERT INTO MINHA_TEMP VALUES(1, 'TESTE2');
INSERT INTO MINHA_TEMP VALUES(1, 'TESTE3');

--ANALIZANDO DADOS DE MINHA_TEMP
SELECT COUNT(*) FROM MINHA_TEMP;

--COMMIT E CHECANDO O CONTEUDO
COMMIT;

--SELECT TABLESPACE_NAME, TABLE_NAME FROM DBA_TABLES WHERE TABLESPACE_NAME='CURSO';

CREATE GLOBAL TEMPORARY TABLE EMPREGADOS_TEMP(
    EMPREGADO_ID NUMBER(6,0) NOT NULL,
    FIRST_NAME VARCHAR2(20 BYTE),
    LAST_NAME VARCHAR2(25 BYTE) NOT NULL,
    COMMISSION_PCT NUMBER(2,2)
    )ON COMMIT DELETE ROWS;
    
INSERT INTO EMPREGADOS_TEMP
    SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.LAST_NAME, A.COMMISSION_PCT
        FROM HR.EMPLOYEES A;
        
SELECT * FROM EMPREGADOS_TEMP;

COMMIT;

DROP TABLE EMPREGADOS_TEMP;
DROP TABLE MINHA_TEMP;